### ISSUE TITLE
Missing libadns1 on stock Oracle Linux

### ISSUE THREAD

**Issue by abaldoni** [graygnuorg/pound#41]
Hi, this is more a comment than an issue ( my 2 cents ).
On stock Oracle Linux there is no official libadns1 package.
It is also missing on all RHEL variants.
I think it should be better to rely on stock libraries for pound dependencies rather than having to build them separately.

**Comment by graygnuorg** [comment]
> On stock Oracle Linux there is no official libadns1 package.
> It is also missing on all RHEL variants.
I'd suggest they'd better add it, as it is available on other Linux distributions.  

> I think it should be better to rely on stock libraries
Depends a great deal on what "stock" really means.  What's "stock" on Debian or Slackware is apparently not "stock" on RHEL :) Seriously, though, DNS resolver libraries are in such short supply, that apart from adns there are not any working alternatives. Short of writing one, of course, which is what I am doing now.  Once it is available, that dependency will go away.

By the way, that library is not a requirement in any way. You will only need it if you plan to use _dynamic backends_, a new feature in this release. Otherwise, pound will happily compile without it.
