### ISSUE TITLE
"HTTP/1.1 303 See Other" wrongly rewritten by pound?

### ISSUE THREAD

**Issue by abaldoni** [graygnuorg/pound#42]
Hi, we are facing a peculiar situation.
A backend is configured to generate a "HTTP/1.1 303 See Other" status on a certain request.
Using wireshark I can see that the URL associated with that status (a redirect to a different domain) is correctly generated and passed to pound.
The clients, however, receive the URL with our company domain.

To better explain:
* the user calls https://our.domain/login
* the backend responds with 303 https://another.domain/speciallogin
* the user gets https://our.domain/speciallogin, which doesn't work.

I am quite sure that with pound 4.12 everything worked fine and that the problem started with pound 4.15 but I'm currently unable to rollback the upgrade.

Kind regards,
Alessandro

**Comment by graygnuorg** [comment]
Hi Alessandro,

Please make sure you have `RewriteLocation 0` in your listener section.

Best regards,
Sergey

**Comment by graygnuorg** [comment]
> I am quite sure that with pound 4.12 everything worked fine and that the
> problem started with pound 4.15 but I'm currently unable to rollback the
> upgrade.

As a matter of fact, the `RewriteLocation` functionality was broken and didn't work as documented for some time.  The problem was fixed in commit 926ab7ebba, and the fix was released with version 4.13 (see the [related entry from its NEWS file](https://github.com/graygnuorg/pound/blob/181117673a00addf61531541f5b6c8bd9799ae86/NEWS#L324)).

Since `RewriteLocation 1` is the default, that fix changed the behavior of existing installation.  I should definitely have described it in more detail in the NEWS.

**Comment by abaldoni** [comment]
Thank you! The configuration is now working as expected.
