### ISSUE TITLE
GPF after a short time

### ISSUE THREAD

**Issue by abaldoni** [graygnuorg/pound#7]
Hi, we are running pound 4.6.90 on Oracle Linux 9 compiled with tcmalloc, openSSL 3.01 and MAXBUF=8192.
After a short time we get a lot of general protection fault errors:

Mar 30 17:09:56 pound-98 pound[26221]: (7f9c30143640) Can't read BIO_f_base64
Mar 30 17:09:56 pound-98 kernel: traps: pound[26228] general protection fault ip:7f9c3086532e sp:7f9c3013fb88 error:0 in libtcmalloc.so.4.5.9[7f9c3083e000+28000]

Any ideas on what to check?

**Comment by graygnuorg** [comment]
I need to see your configuration file in order to advice. And the commit id (if you did git clone). The former is a security-sensitive issue, so if you are going to post it here, be sure to censor out any sensitive information.  Otherwise, you can gpg-encrypt it with my key (79FFD94BFCE230B1) and send it over to my private email.  The latter can be obtained by `git describe` in the top-level source directory.

**Comment by graygnuorg** [comment]
Thanks for your mail, Alessandro. I have pushed the commit e15ee89d82d36be0b47d65a53ba0b92301e53900, which should fix the bug. Please, pull, recompile and retry. Let me know if it works for you.

**Comment by abaldoni** [comment]
Thank Sergey, we rebuilt pound with your commit and, up to now, have experienced no errors.

Thank you so much!
